# NumPy Practice Notebook

This notebook demonstrates NumPy fundamentals for numerical data analysis, including array creation, indexing, reshaping, generation functions, vectorized math, boolean masking, broadcasting, and aggregate functions.

In [24]:
import numpy as np
print('NumPy version:', np.__version__)

NumPy version: 2.3.5


## 1D Arrays

Create and inspect one-dimensional NumPy arrays.

In [25]:
arr1d = np.array([10, 20, 30, 40, 50])
print('Array:', arr1d)
print('ndim:', arr1d.ndim)
print('shape:', arr1d.shape)
print('dtype:', arr1d.dtype)

Array: [10 20 30 40 50]
ndim: 1
shape: (5,)
dtype: int64


## 2D Arrays

Create and inspect two-dimensional arrays (matrices).

In [26]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print('2D array:', arr2d)
print('ndim:', arr2d.ndim)
print('shape:', arr2d.shape)
print('dtype:', arr2d.dtype)

2D array: [[1 2 3]
 [4 5 6]
 [7 8 9]]
ndim: 2
shape: (3, 3)
dtype: int64


## 3D Arrays

Create and inspect three-dimensional arrays.

In [27]:
arr3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print('3D array:', arr3d)
print('ndim:', arr3d.ndim)
print('shape:', arr3d.shape)
print('dtype:', arr3d.dtype)

3D array: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
ndim: 3
shape: (2, 2, 2)
dtype: int64


## Indexing and Slicing

Access elements and subarrays using indexing and slicing.

In [28]:
print('First element of arr1d:', arr1d[0])
print('Last element of arr1d:', arr1d[-1])
print('Slice arr1d[1:4]:', arr1d[1:4])
print('\nRow 2 of arr2d:', arr2d[1])
print('Element [2,1] of arr2d:', arr2d[2, 1])
print('Submatrix of arr2d rows 0:2, cols 1:3:\n', arr2d[0:2, 1:3])
print('\nSlice from arr3d:\n', arr3d[0, :, 1])

First element of arr1d: 10
Last element of arr1d: 50
Slice arr1d[1:4]: [20 30 40]

Row 2 of arr2d: [4 5 6]
Element [2,1] of arr2d: 8
Submatrix of arr2d rows 0:2, cols 1:3:
 [[2 3]
 [5 6]]

Slice from arr3d:
 [2 4]


## Reshaping Arrays

Change the shape of arrays without copying data.

In [29]:
reshaped = np.arange(12)
print('Original array:', reshaped)
reshaped = reshaped.reshape((3, 4))
print('Reshaped to 3x4:', reshaped)
print('Flattened back:', reshaped.ravel())

Original array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped to 3x4: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened back: [ 0  1  2  3  4  5  6  7  8  9 10 11]


## Generating Arrays

Use convenience functions such as zeros(), ones(), arange(), and linspace().

In [30]:
zeros_arr = np.zeros((2, 3))
ones_arr = np.ones((2, 3), dtype=int)
arange_arr = np.arange(5, 16, 2)
linspace_arr = np.linspace(0, 1, 6)
print('zeros_arr:', zeros_arr)
print('ones_arr:', ones_arr)
print('arange_arr:', arange_arr)
print('linspace_arr:', linspace_arr)

zeros_arr: [[0. 0. 0.]
 [0. 0. 0.]]
ones_arr: [[1 1 1]
 [1 1 1]]
arange_arr: [ 5  7  9 11 13 15]
linspace_arr: [0.  0.2 0.4 0.6 0.8 1. ]


## Mathematical and Vectorized Operations

Perform arithmetic and elementwise operations efficiently.

In [31]:
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])
print('a + b:', a + b)
print('a * b:', a * b)
print('a squared:', a ** 2)
print('sin of a:', np.sin(a))
print('Square root of b:', np.sqrt(b))

a + b: [11 22 33 44]
a * b: [ 10  40  90 160]
a squared: [ 1  4  9 16]
sin of a: [ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
Square root of b: [3.16227766 4.47213595 5.47722558 6.32455532]


## Boolean Masking

Filter arrays using boolean conditions.

In [32]:
mask = arr2d > 5
print('Mask for arr2d > 5:', mask)
print('Values greater than 5:', arr2d[mask])

Mask for arr2d > 5: [[False False False]
 [False False  True]
 [ True  True  True]]
Values greater than 5: [6 7 8 9]


## Broadcasting

Apply operations between arrays with compatible shapes.

In [33]:
row = np.array([1, 2, 3])
matrix = np.array([[10, 20, 30], [40, 50, 60]])
print('matrix:', matrix)
print('row:', row)
print('matrix + row:', matrix + row)
scalar = 5
print('matrix + scalar:', matrix + scalar)

matrix: [[10 20 30]
 [40 50 60]]
row: [1 2 3]
matrix + row: [[11 22 33]
 [41 52 63]]
matrix + scalar: [[15 25 35]
 [45 55 65]]


## Aggregate Functions

Use common reductions to summarize data.

In [34]:
print('arr2d sum:', np.sum(arr2d))
print('arr2d mean:', np.mean(arr2d))
print('arr2d min:', np.min(arr2d))
print('arr2d max:', np.max(arr2d))
print('arr2d median:', np.median(arr2d))
print('sum by column:', np.sum(arr2d, axis=0))
print('mean by row:', np.mean(arr2d, axis=1))

arr2d sum: 45
arr2d mean: 5.0
arr2d min: 1
arr2d max: 9
arr2d median: 5.0
sum by column: [12 15 18]
mean by row: [2. 5. 8.]
